name: AdminMail
main: AdminMail\Main
api: [3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7]
version: 0.0.3
description: "Administrative email on events"

commands:
  mail:
    description: "Root command"
    permission: mail.permission

permissions:
  mail.permission:
    default: op
    description: "Allow user to use this plugin"